### ISSUE TITLE
High CPU Usage When Called from Background

### ISSUE THREAD

**Issue by RoeeNadam** [CocoaBeans/Pinglet#1]
My iOS app experiences occasional high CPU usage, which sometimes occurs after two background calls to the Pinglet service and may, at times, take longer to manifest. even when the app is not actively in the foreground. The elevated CPU usage can impact the overall performance of the device and potentially result in reduced battery life.

I try with DispatchQueue.global() and   
 let SERIAL_QUEUE = DispatchQueue(label: "PINGER_SERIAL_QUEUE", qos: .background)
but same result.
![Screenshot 2023-09-03 at 8 52 08](https://github.com/CocoaBeans/Pinglet/assets/16390768/a42227cf-4f24-41d6-a74a-617cbfcf3d82)

<img width="725" alt="Screenshot 2023-09-03 at 8 43 36" src="https://github.com/CocoaBeans/Pinglet/assets/16390768/0fd75dcb-80d8-434c-946b-3ac8e5b691a6">

**Comment by CocoaBeans** [comment]
Thank you for your report. Are you able to provide that instruments trace file? Are you creating a new ping instance every time or are you letting the same ping instance run continuously? If you're letting it run continuously how long are you letting it run for?

From the screenshot it looks like a lot of work is happening in the closure callbacks (specifically bridging to/from objc) which looks different to the stack traces in the app that I'm using this in (https://pingpoint.io).

**Comment by CocoaBeans** [comment]
Can you show a redacted version of your closure callbacks? It's possible that if the work done in the didSend/didRecieve callbacks takes too long to complete it could end up blocking that internal serial queue.

**Comment by CocoaBeans** [comment]
I just re-read your comment, are you making TWO ping instances at the same time?

**Comment by RoeeNadam** [comment]
First thank you for the quick response !
I try to work with one instance or not, and with 'Ping' once. But after some time, the app is in the background, my app is triggered by Bluetooth to start 'Ping' when the app is still in the background, and during this time, the CPU starts to freak out.

This is my code, I call start from background when Bluetooth connect or something like this, and I close the peripheral, after a few times like this (call start a few times with delay 1-30 minutes ) the app freak.


import Foundation
import Pinglet

class Pinger {
    static let sharedInstance = Pinger()
    private init() {}
    
    private var pinglet: Pinglet?
//    let SERIAL_QUEUE = DispatchQueue(label: "PINGER_SERIAL_QUEUE", qos: .background)
    
    func start(_ duration: Double) {
        if pinglet == nil {
            print("pinglet ping init !!!!!!!!!!!!!!!!!!!!!! ")
            pinglet = try? Pinglet(host: "8.8.8.8",
                                         configuration: PingConfiguration(interval: Config.Ping.interval),
                                         queue: DispatchQueue.global())
        }
        try? pinglet?.startPinging()
    }
}

**Comment by CocoaBeans** [comment]
Are you calling `pinglet?.startPinging()` again without calling `pinglet?.stopPinging()` before? In a quick test I'm seeing it start another ping session on that same socket each time `startPinging()` is called without a matching `stopPinging()`. I'll go ahead and change the default behavior to not start pinging again if it is already started to be safe.

**Comment by CocoaBeans** [comment]
Try testing with https://github.com/CocoaBeans/Pinglet/commit/96d3059eb6b7064b8220d98d6fd8ff3421fe2d4f and see if you are still seeing the same problem.

**Comment by RoeeNadam** [comment]
This is the previous version, but the problem still persists

    func start(_ duration: Double) {
        stop()
        Logger.log("Coorelation ping start")
        AudioManager.shared.playPingSound()
        
        if pinglet == nil {
            print("pinglet ping init !!!!!!!!!!!!!!!!!!!!!! ")
            pinglet = try? Pinglet(host: "8.8.8.8",
                                         configuration: PingConfiguration(interval: Config.Ping.interval),
                                         queue: DispatchQueue.global())
        }
        print("pinglet ping start = \(pinglet)")
        try? pinglet?.startPinging()
        AudioManager.shared.playPingSound()
        Logger.log("Coorelation ping start")
        pingTimer = Timer.scheduledTimer(timeInterval: duration, target: self,
                                         selector: #selector(stop(_:)), userInfo: nil, repeats: false)
    }
    
    @objc func stop(_ timer: Timer? = nil) {
        if timer != nil {
            Logger.log("Coorelation ping ended")
        }
        pingTimer?.invalidate()
        pingTimer = nil
        pinglet?.stopPinging()
        print("pinglet ping stop !! = \(pinglet)")
    }

**Comment by RoeeNadam** [comment]
Now, I'm trying to test with the new version.

**Comment by RoeeNadam** [comment]
still happened :-(
send you instruments file to kevin@pingpoint.io

**Comment by CocoaBeans** [comment]
Thank you for the details! How are you calling into these functions from your background process? I'm seeing multiple calls to `__NSThread__start__` in the trace and my hunch is that there are multiple threads being started for the same instance somehow.

**Comment by CocoaBeans** [comment]
I haven't done much testing outside of my use case since I forked the original project. There is some code that only runs on iOS when it moves to the background that will automatically disable the pings. There might be a bug unless it is deactivated. Try setting `pinglet.allowBackgroundPinging = true` and see if you have any better luck.

**Comment by RoeeNadam** [comment]
From here, I call the 'pinglet' to start. If my Bluetooth device wants me to start pinging, I use the 'peripheral(_ peripheral: CBPeripheral, didUpdateValueFor characteristic: CBCharacteristic, error: Error?)' function. It's very weird that it still pings without setting this flag to true. I will now check by setting this flag to true.

**Comment by RoeeNadam** [comment]
still happened with this - pinglet.allowBackgroundPinging = true

**Comment by CocoaBeans** [comment]
Thank you for the details! I'm seeing a bug where the background thread is not exiting and cleaning up correctly in the stopPing() function. In my app I create a new ping instance every time the user initiates a new ping so this has remained hidden until now. I'm working on a fix and will get back to you ASAP when I've tracked down the problem. Thank you!

**Comment by CocoaBeans** [comment]
I have fixed several bugs that I'm fairly confident would be causing the issue that you're seeing! Try your app with the fixes in https://github.com/CocoaBeans/Pinglet/commit/a7b76a3780bd1822c1f0001c95574e2300217cd7 and let me know if it works any better.

**Comment by RoeeNadam** [comment]
Thank you for your efforts in addressing the issues. I'll definitely give the fixes in commit a7b76a3 a try and let you know how the app performs. I appreciate your help with this!
